version: '3.8'

services:
  admin-frontend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: admin-frontend
    networks:
      - frontend-network

  user-frontend:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: user-frontend
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge